# -*- coding: utf-8 -*-
"""extract data from YH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTHm5b9YE1ecXOMg7MfuNZdtpJAf4Uiy
"""

import requests
from bs4 import BeautifulSoup

def yahoo_growth(sym):
    """Use BeautifulSoup to obtain analyst growth rate from Yahoo Finance"""
    url = f"https://finance.yahoo.com/quote/{sym}/analysis?p={sym}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
    }

    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        raise Exception(f"Failed to load page: {url}")

    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table that contains the growth estimates
    tables = soup.find_all('table')

    # Usually, the Growth Estimates table is the last one on the page
    growth_table = tables[-2]  # The growth estimates table is the last second table

    # Find the row corresponding to the next 5 years' growth rate
    rows = growth_table.find_all('tr')
    for row in rows:
        if 'Next 5 Years (per annum)' in row.text:
            growth_rate = row.find_all('td')[1].text
            break
    else:
        raise Exception("Could not find growth rate row.")

    # # Convert the growth rate to a float and return it
    growth_rate = float(growth_rate.replace('%', '')) / 100

    return growth_rate
    # return growth_table

# Call the function with the stock symbol and print the result
sym = "AAPL"
growth_rate = yahoo_growth(sym)
print(f"Analyst Growth Rate for {sym}: {growth_rate:.2%}")
# growth_rate

